export const GARAGE_CARS = [
  {
    make: "McLaren",
    analyticsCar: "mclaren",
    model: "720S",
    name: "McLaren 720S",
    image: "/media/v2/mclaren-gulf.webp",
    alt: "Gulf racing blue McLaren 720S Coupe",
    character: "Sculpted by the air.",
    engine: "Twin-turbo V8",
    spirit: "Supercar",
    study: "Form follows feeling.",
    copy: "Every curve has a purpose. Every open road is an invitation.",
  },
  {
    make: "Porsche",
    analyticsCar: "porsche",
    model: "911 GT3 RS",
    name: "Porsche 911 GT3 RS",
    image: "/media/v3/porsche-oak-green.webp",
    alt: "Oak Green Metallic Porsche 911 GT3 RS with bronze wheels in a dark studio",
    character: "Every corner, a conversation.",
    engine: "Naturally aspirated flat-six",
    spirit: "Precision",
    study: "An obsession with the next corner.",
    copy: "A singular obsession with the way a car feels in your hands.",
  },
  {
    make: "Ferrari",
    analyticsCar: "ferrari",
    model: "458 Italia",
    name: "Ferrari 458 Italia",
    image: "/media/car-ferrari.webp",
    alt: "Ferrari 458 nose and prancing horse badge in a warm studio study",
    character: "Some things need no translation.",
    engine: "Naturally aspirated V8",
    spirit: "Emotion",
    study: "A language all its own.",
    copy: "The prancing horse. The unmistakable voice. The reason you take the long way.",
  },
];
